/**
 *SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
/**
 * Creates a instance of Category
 *
 * @constructor
 */

angular.module('SwaggerPetstoreLib').factory('Category',function(BaseModel){
	var Category = function(obj) {
		if(!obj){
						this.id = null;     
    				this.name = null;     
    													
		}
		else
		{
					this.id = obj.id;
    		this.name = obj.name;
 
		}
	}

	Category.prototype = new BaseModel();
	Category.prototype.constructor = Category;

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {long|null}
	 */
	Category.prototype.getId = function() {
		return this.id;
	};

	/**
	 * Setter for Id
	 * 
	 * @param {long|null} value 
	 */
	Category.prototype.setId = function(value) {
		this.id = value;
	};

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {string|null}
	 */
	Category.prototype.getName = function() {
		return this.name;
	};

	/**
	 * Setter for Name
	 * 
	 * @param {string|null} value 
	 */
	Category.prototype.setName = function(value) {
		this.name = value;
	};

	
	return Category;
});