/**
  *SwaggerPetstoreLib
  *
  *This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
  */


angular.module('SwaggerPetstoreLib').factory('Status6Enum', function() {
    return {

        //TODO: Write general description for this element    
        AVAILABLE : "available",

        //TODO: Write general description for this element    
        PENDING : "pending",

        //TODO: Write general description for this element    
        SOLD : "sold",
    };
});