/**
 *SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */

'use strict';
angular.module('SwaggerPetstoreLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://petstore.swagger.io/v2",

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the oAuthAccessToken with an appropriate value
        oAuthAccessToken : "TODO: Replace"

    };
});

